### PR TITLE
Sync with main branch 

### PR DESCRIPTION
**Pull request by VedantMahabaleshwarkar**
## Description

Sync with main branch for ODH 2.18 release

### CODE REVIEW

**Comment by israel-hdez** [comment]
AFAIK, we don't sync with `main`. I think this should be closed.

**Comment by spolti** [comment]
@israel-hdez can you please elaborate? I've done this a few times already, not sure why we don't do this.

**Comment by israel-hdez** [comment]
@spolti Similarly to KServe, we base our ODH release on an upstream release.
By pulling changes from `main` into the release branch our release is no longer based on an upstream release, but just on latest code. Thus, the release branch no longer makes sense and we could simply release from `main`, which is not our current goal.

**Comment by spolti** [comment]
ohhh right lol
I didn't pay attention to the target branch, indeed, we can close this.

**Pull request closed without merging**
