### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by VedantMahabaleshwarkar — APPROVED** [review]
/lgtm

**Comment by Jooho** [comment]
@vaibhavjainwiz  The fvt test will be failed because it uses the wrong modelmesh-serving-develop image. This pr will solve the issue.: https://github.com/openshift/release/pull/43449

**Pull request merged**
